version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app/server  # Only mount server directory
    ports:
      - "5174:5173"  # Map host 5174 to container 5173 (Vite)
      - "3001:80"    # Map host 3001 to container 80 (Backend)
    environment:
      - DATABASE_URL=postgresql://postgres:kevjeff1@db:5432/carwash_dev
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    working_dir: /app/server
    entrypoint: ["/usr/local/bin/dev-entrypoint.sh"]
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kevjeff1
      - POSTGRES_DB=carwash_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redisdata_dev:/data

volumes:
  pgdata_dev:
  redisdata_dev: